services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pdf-reader-ui
    ports:
      - "5173:5173"
    environment:
      - VITE_WATCH=true
    volumes:
      - .:/app
      - /app/node_modules
